name: mudblazor-ci

'on':
  push:
    branches: [ dev ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
      - name: Install and build all templates
        shell: pwsh
        run: |
          ./InstallAndBuildAllTemplates.ps1
